### PR TITLE
Linguistic tweaks

### PR DESCRIPTION
**Pull request by esttorhe**
Cleaned up the repo's language statistics.

---

screen shot 2015-07-29 at 14 35 22

### CODE REVIEW

**Comment by cojoj** [comment]
@esttorhe's back! 🎉

**Comment by esttorhe** [comment]
:joy: yeah; trying to find time to work on `OSS` again ;)

**Comment by czechboy0** [comment]
:+1:

**Comment by czechboy0** [comment]
Now that you sneaked into _contributors_, feel free to take a look at API blueprint and help us document this thing :smile: There are still easy and quick ones. Need documentation for documentation? 

`/Applications/Xcode-beta.app/Contents/Developer/usr/share/xcs/xcsd/routes`

Welcooooome :fireworks:

**Comment by esttorhe** [comment]
hahahaha; I was actually looking at the blueprint (can't get over how pretty it is every time I have to use one).

Sooooooo; which ones are missing? :flushed:

**Comment by czechboy0** [comment]
Well, let's put it this way. Look at the readme, and the ones with :white_check_mark: are documented. The rest... isn't _yet_. The way we do it - edit the blueprint, add the documentation there. Once happy, add the :white_check_mark: in the readme (and if the header doesn't link to the section yet, add that, see Bots for instance). Then PR this whole thing. Installing `apiary` tool will make it possible to preview locally, which makes it much easier. It even does automatic linting when writing in sublime text.

**Comment by esttorhe** [comment]
:bow: awesome sauce.

I'll take a look at that README then

**Pull request merged**
